did_ranges = {
    (0x0000, 0x00FF): 'ISOSAEReserved'),
    (0x0100, 0xEFFF): 'vehicleManufacturerSpecific'),
    (0xF000, 0xF00F): 'networkConfigurationDataForTractorTrailerApplicationDataIdentifier'),
    (0xF010, 0xF0FF): 'vehicleManufacturerSpecific'),
    (0xF100, 0xF17F): 'identificationOptionVehicleManufacturerSpecificDataIdentifier'),
    (0xF180,): 'bootSoftwareIdentificationDataIdentifier'),
    (0xF181,): 'applicationSoftwareIdentificationDataIdentifier'),
    (0xF182,): 'applicationDataIdentificationDataIdentifier'),
    (0xF183,): 'bootSoftwareFingerprintDataIdentifier'),
    (0xF184,): 'applicationSoftwareFingerprintDataIdentifier'),
    (0xF185,): 'applicationDataFingerprintDataIdentifier'),
    (0xF186,): 'activeDiagnosticSessionDataIdentifier'),
    (0xF187,): 'vehicleManufacturerSparePartNumberDataIdentifier'),
    (0xF188,): 'vehicleManufacturerECUSoftwareNumberDataIdentifier'),
    (0xF189,): 'vehicleManufacturerECUSoftwareVersionNumberDataIdentifier'),
    (0xF18A,): 'systemSupplierIdentifierDataIdentifier'),
    (0xF18B,): 'ECUManufacturingDateDataIdentifier'),
    (0xF18C,): 'ECUSerialNumberDataIdentifier'),
    (0xF18D,): 'supportedFunctionalUnitsDataIdentifier'),
    (0xF18E,): 'vehicleManufacturerKitAssemblyPartNumberDataIdentifier'),
    (0xF18F,): 'ISOSAEReservedStandardized'),
    (0xF190,): 'VINDataIdentifier'),
    (0xF191,): 'vehicleManufacturerECUHardwareNumberDataIdentifier'),
    (0xF192,): 'systemSupplierECUHardwareNumberDataIdentifier'),
    (0xF193,): 'systemSupplierECUHardwareVersionNumberDataIdentifier'),
    (0xF194,): 'systemSupplierECUSoftwareNumberDataIdentifier'),
    (0xF195,): 'systemSupplierECUSoftwareVersionNumberDataIdentifier'),
    (0xF196,): 'exhaustRegulationOrTypeApprovalNumberDataIdentifier'),
    (0xF197,): 'systemNameOrEngineTypeDataIdentifier'),
    (0xF198,): 'repairShopCodeOrTesterSerialNumberDataIdentifier'),
    (0xF199,): 'programmingDateDataIdentifier'),
    (0xF19A,): 'calibrationRepairShopCodeOrCalibrationEquipmentSerialNumberData- Identifier'),
    (0xF19B,): 'calibrationDateDataIdentifier'),
    (0xF19C,): 'calibrationEquipmentSoftwareNumberDataIdentifier'),
    (0xF19D,): 'ECUInstallationDateDataIdentifier'),
    (0xF19E,): 'ODXFileDataIdentifier'),
    (0xF19F,): 'entityDataIdentifier'),
    (0xF1A0, 0xF1EF): 'identificationOptionVehicleManufacturerSpecific'),
    (0xF1F0, 0xF1FF): 'identificationOptionSystemSupplierSpecific'),
    (0xF200, 0xF2FF): 'periodicDataIdentifier'),
    (0xF300, 0xF3FF): 'dynamicallyDefinedDataIdentifier'),
    (0xF400, 0xF4FF): 'OBDDataIdentifier'),
    (0xF500, 0xF5FF): 'OBDDataIdentifier'),
    (0xF600, 0xF6FF): 'OBDMonitorDataIdentifier'),
    (0xF700, 0xF7FF): 'OBDMonitorDataIdentifier'),
    (0xF800, 0xF8FF): 'OBDInfoTypeDataIdentifier'),
    (0xF900, 0xF9FF): 'TachographDataIdentifier'),
    (0xFA00, 0xFA0F): 'AirbagDeploymentDataIdentifier'),
    (0xFA10, 0xFAFF): 'SafetySystemDataIdentifier'),
    (0xFB00, 0xFCFF): 'ReservedForLegislativeUse'),
    (0xFD00, 0xFEFF): 'SystemSupplierSpecific'),
    (0xFF00, 0xFFFF): 'ISOSAEReserved'),
}
